manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kblack0610
      url-base: https://github.com/kblack0610
    - name: whoop-t
      url-base: https://github.com/whoop-t
    - name: scybin
      url-base: https://github.com/scybin
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: nice-one-punch-ok
      remote: whoop-t
      revision: main
    - name: zmk-driver-pim447
      remote: scybin
      revision: master
  self:
    path: config
